version: "3"

services: 
  
    web-mvc:
        image: desenvolvedorio/nerdstore-web-mvc-ecommerce:latest
        container_name: nerdstore-web-mvc-ecommerce
        build:
            context: ../src
            dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
        ports:
          - "5001:5001"
          - "5003:5003"
        environment:
          - ASPNETCORE_ENVIRONMENT=Production
          - ASPNETCORE_URLS=http://*:5001